<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $this->_block \Magento\Backend\Block\Store\Switcher */
?>

<?php if ($websites = $this->_block->getWebsites()): ?>
<tr id="row_triggmine_connector_api_credentials_scope_switcher">
    <td colspan="5">
<?php if ($this->_currentWebsiteId): ?>
    <div class="store-switcher store-view">
        <span class="store-switcher-label"><?php /* @escapeNotVerified */ echo __('To procceed to export settings please select the store:') ?></span>
        <div class="actions dropdown closable">
            <input type="hidden" name="store_switcher" id="store_switcher"
                   data-role="store-view-id" data-param="<?php /* @escapeNotVerified */ echo $this->_block->getStoreVarName() ?>"
                   value="<?php echo $this->_block->escapeHtml($this->_block->getStoreId()) ?>"
                   onchange="switchScopeForTriggmine(this);"<?php /* @escapeNotVerified */ echo $this->_block->getUiId()?> />
            <input type="hidden" name="store_group_switcher" id="store_group_switcher"
                   data-role="store-group-id" data-param="<?php /* @escapeNotVerified */ echo $this->_block->getStoreGroupVarName() ?>"
                   value="<?php echo $this->_block->escapeHtml($this->_block->getStoreGroupId()) ?>"
                   onchange="switchScopeForTriggmine(this);"<?php /* @escapeNotVerified */ echo $this->_block->getUiId()?> />
            <input type="hidden" name="website_switcher" id="website_switcher"
                   data-role="website-id" data-param="<?php /* @escapeNotVerified */ echo $this->_block->getWebsiteVarName() ?>"
                   value="<?php echo $this->_block->escapeHtml($this->_block->getWebsiteId()) ?>"
                   onchange="switchScopeForTriggmine(this);"<?php /* @escapeNotVerified */ echo $this->_block->getUiId()?> />
            <button
                type="button"
                class="admin__action-dropdown"
                data-mage-init='{"dropdown":{}}'
                data-toggle="dropdown"
                aria-haspopup="true"
                id="store-change-button">
                <?php /* @escapeNotVerified */ echo $this->_block->getDefaultSelectionName() ?>
            </button>
            <ul class="dropdown-menu" data-role="stores-list">
                <?php if ($this->_block->hasDefaultOption()): ?>
                    <li class="store-switcher-all disabled <?php if ( ! $this->_block->hasScopeSelected()) {
                        ?> current<?php
                    } ?>">
                        <span><?php /* @escapeNotVerified */ echo $this->_block->getDefaultSelectionName() ?></span>
                    </li>
                <?php endif; ?>
                <?php foreach ($websites as $website): ?>
                    <?php $showWebsite = false; ?>
                    <?php if ($website->getId() == $this->_currentWebsiteId): ?>
                        <?php foreach ($website->getGroups() as $group): ?>
                            <?php $showGroup = false; ?>
                            <?php foreach ($this->_block->getStores($group) as $store): ?>
                                <li class="store-switcher-store-view <?php if ( ! ($this->_block->isStoreSwitchEnabled() && ! $this->_block->isStoreSelected($store))) {
                                    echo "disabled";
                                } ?> <?php if ($this->_block->isStoreSelected($store)) {
                                    ?> current<?php
                                } ?>">
                                    <?php if ($this->_block->isStoreSwitchEnabled() && ! $this->_block->isStoreSelected($store)) {
                                        ?>
                                        <a data-role="store-view-id" data-value="<?php echo $this->_block->escapeHtml($store->getId()) ?>" href="#">
                                            <?php echo $this->_block->escapeHtml($store->getName()) ?>
                                        </a>
                                    <?php
                                    } else {
                                        ?>
                                        <span><?php echo $this->_block->escapeHtml($store->getName()) ?></span>
                                    <?php
                                    } ?>
                                </li>
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($this->_block->getShowManageStoresLink() && $this->_block->getAuthorization()->isAllowed('Magento_Backend::store')): ?>
                    <li class="dropdown-toolbar">
                        <a href="<?php /* @escapeNotVerified */ echo $this->_block->getUrl('*/system_store') ?>"><?php /* @escapeNotVerified */ echo __('Stores Configuration') ?></a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
<?php else: ?>
    <div class="store-switcher store-view">
        <span class="store-switcher-label"><?php /* @escapeNotVerified */ echo __('Please select the website where you want to use Triggmine:') ?></span>
        <div class="actions dropdown closable">
            <input type="hidden" name="store_switcher" id="store_switcher"
                   data-role="store-view-id" data-param="<?php /* @escapeNotVerified */ echo $this->_block->getStoreVarName() ?>"
                   value="<?php echo $this->_block->escapeHtml($this->_block->getStoreId()) ?>"
                   onchange="switchScopeForTriggmine(this);"<?php /* @escapeNotVerified */ echo $this->_block->getUiId()?> />
            <input type="hidden" name="store_group_switcher" id="store_group_switcher"
                   data-role="store-group-id" data-param="<?php /* @escapeNotVerified */ echo $this->_block->getStoreGroupVarName() ?>"
                   value="<?php echo $this->_block->escapeHtml($this->_block->getStoreGroupId()) ?>"
                   onchange="switchScopeForTriggmine(this);"<?php /* @escapeNotVerified */ echo $this->_block->getUiId()?> />
            <input type="hidden" name="website_switcher" id="website_switcher"
                   data-role="website-id" data-param="<?php /* @escapeNotVerified */ echo $this->_block->getWebsiteVarName() ?>"
                   value="<?php echo $this->_block->escapeHtml($this->_block->getWebsiteId()) ?>"
                   onchange="switchScopeForTriggmine(this);"<?php /* @escapeNotVerified */ echo $this->_block->getUiId()?> />
            <button
                type="button"
                class="admin__action-dropdown"
                data-mage-init='{"dropdown":{}}'
                data-toggle="dropdown"
                aria-haspopup="true"
                id="store-change-button">
                <?php /* @escapeNotVerified */ echo $this->_block->getCurrentSelectionName() ?>
            </button>
            <ul class="dropdown-menu" data-role="stores-list">
                <?php if ($this->_block->hasDefaultOption()): ?>
                    <li class="store-switcher-all <?php if ( ! ($this->_block->getDefaultSelectionName() != $this->_block->getCurrentSelectionName())) {
                        echo "disabled";
                    } ?> <?php if ( ! $this->_block->hasScopeSelected()) {
                        ?> current<?php
                    } ?>">
                        <?php if ($this->_block->getDefaultSelectionName() != $this->_block->getCurrentSelectionName()) {
                            ?>
                            <a data-role="store-view-id" data-value="" href="#">
                                <?php /* @escapeNotVerified */ echo $this->_block->getDefaultSelectionName() ?>
                            </a>
                        <?php
                        } else {
                            ?>
                            <span><?php /* @escapeNotVerified */ echo $this->_block->getDefaultSelectionName() ?></span>
                        <?php
                        } ?>
                    </li>
                <?php endif; ?>
                <?php foreach ($websites as $website): ?>
                    <?php $showWebsite = false; ?>
                    <?php foreach ($website->getGroups() as $group): ?>
                        <?php $showGroup = false; ?>
                        <?php foreach ($this->_block->getStores($group) as $store): ?>
                            <?php if ($showWebsite == false): ?>
                                <?php $showWebsite = true; ?>
                                <li class="store-switcher-website <?php if ( ! ($this->_block->isWebsiteSwitchEnabled() && ! $this->_block->isWebsiteSelected($website))) {
                                    echo "disabled";
                                } ?> <?php if ($this->_block->isWebsiteSelected($website)) {
                                    ?> current<?php
                                } ?>">
                                    <?php if ( ! $this->_block->isWebsiteSelected($website)) {
                                        ?>
                                        <a data-role="website-id" data-value="<?php echo $this->_block->escapeHtml($website->getId()) ?>" href="#">
                                            <?php echo $this->_block->escapeHtml($website->getName()) ?>
                                        </a>
                                    <?php
                                    } else {
                                        ?>
                                        <span><?php echo $this->_block->escapeHtml($website->getName()) ?></span>
                                    <?php
                                    } ?>
                                </li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                <?php endforeach; ?>
                <?php if ($this->_block->getShowManageStoresLink() && $this->_block->getAuthorization()->isAllowed('Magento_Backend::store')): ?>
                    <li class="dropdown-toolbar">
                        <a href="<?php /* @escapeNotVerified */ echo $this->_block->getUrl('*/system_store') ?>"><?php /* @escapeNotVerified */ echo __('Stores Configuration') ?></a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
    </td>
</tr>

<script>
require([
    'jquery',
    'Magento_Ui/js/modal/confirm'
], function(jQuery, confirm){

    (function($) {
        var $storesList = $('[data-role=stores-list]');
        $storesList.on('click', '[data-value]', function(event) {
            var val = $(event.target).data('value');
            var role = $(event.target).data('role');
            var switcher = $('[data-role='+role+']');

            event.preventDefault();

            if (!switcher.val() || val != switcher.val()) {
                switcher.val(val).trigger('change'); // Set the value & trigger event
            }
        });
    })(jQuery);

    var scopeSwitcherHandler;

    function switchScopeForTriggmine(obj) {
        var switcher = jQuery(obj);
        var scopeId = switcher.val();
        var scopeParams = '';
        if (scopeId) {
            scopeParams = switcher.data('param') + '/' + scopeId + '/';
        }

        if (obj.switchParams) {
            scopeParams += obj.switchParams;
        }

        if ((typeof scopeSwitcherHandler) != 'undefined') {
            var switcherParams = {
                scopeId: scopeId,
                scopeParams: scopeParams,
                useConfirm: 0
            };
            scopeSwitcherHandler(switcherParams);
        } else {
            reload();
        }

        function reload() {
            <?php if (!$this->_block->isUsingIframe()): ?>
            var url = '<?php /* @escapeNotVerified */ echo $this->_block->getSwitchUrl() ?>' + scopeParams;
            setLocation(url);
            <?php else: ?>
            jQuery('#preview_selected_store').val(scopeId);
            jQuery('#preview_form').submit();

            jQuery('.store-switcher .dropdown-menu li a').each(function() {
                var $this = jQuery(this);

                if ($this.data('role') === 'store-view-id' && $this.data('value') == scopeId) {
                    jQuery('#store-change-button').html($this.text());
                }
            });

            jQuery('#store-change-button').click();
            <?php endif; ?>
        }
    }
    
    window.bind('beforeunload', function(){
      return 'Are you sure you want to leave?';
    });
    
    window.scopeSwitcherHandler = scopeSwitcherHandler;
    window.switchScopeForTriggmine = switchScopeForTriggmine;

});
</script>
<?php endif; ?>

<style type="text/css">
    #row_triggmine_connector_api_credentials_scope_switcher .admin__action-dropdown:after, #row_triggmine_connector_api_credentials_scope_switcher .admin__action-dropdown:after {
        transform: rotate(0);
    }
    
    #row_triggmine_connector_api_credentials_scope_switcher ._active .admin__action-dropdown:after, #row_triggmine_connector_api_credentials_scope_switcher .active .admin__action-dropdown:after {
        transform: rotate(180deg);
    }
</style>
