<?php if ($this->helper('Triggmine\Connector\Helper\Data')->isEnabled()): ?>
    <script type="text/javascript">
        /*global require*/
        require(['fingerprint2', 'jscookie', 'clientjs'], function(Fingerprint2, Cookies)
        {   
            /*global ClientJS*/
            var a = {
                    swfPath: '/assets/FontList.swf',
                    excludeUserAgent: !0,
                    excludeLanguage: !0,
                    extendedJsFonts: 0
                },
                b = new ClientJS,
                c = b.getFingerprint();
            
            Cookies.set('device_id_1', c, {
                path: '/',
                expires: 7
            }), new Fingerprint2(a).get(function(a) {
                Cookies.set('device_id', a, {
                    path: '/',
                    expires: 7
                });
            });
        });
    </script>
<?php else: ?>
<!-- TriggMine module is not used! -->
<script type="text/javascript">
//<![CDATA[
    console.warn("TriggMine module is not used!");
//]]
</script>
<?php endif; ?>
